### ISSUE TITLE
Add RESTful routes 

### ISSUE THREAD

**Issue by SalahEddineBC** [ScientificClubofESI/EasyHack#1]
We might have a mobile application for the platform , so the backend should have routes that can be reached by mobile clients

**Comment by zeabdelkhalek** [comment]
Unfortunately, we don't have plans to port this app to mobile at the moment !

**Comment by MiloudiMohamed** [comment]
Would you merge a PR fixing this ? (I don't want to spend my time and then it get rejected)

**Comment by SalahEddineBC** [comment]
As my mate told you , we dont have a plan for a mobile app , but we wont reject it , it might be open for a long time but whenever we will plan to expand our app , we will absolutly merge your PR , looking forward for your contribution :D

**Comment by AdelNamani** [comment]
It would be a nice addition to the project , fork the project and show us how great you can do !
