### ISSUE TITLE
Dockerize LaraHack

### ISSUE THREAD

**Issue by th3happybit** [ScientificClubofESI/EasyHack#3]
I think that we should dockerize this app to make it easy to deploy.

**Comment by zeabdelkhalek** [comment]
Yes , it's a good idea , you are welcome to work on it if u can .

**Comment by th3happybit** [comment]
> Yes, it's a good idea, you are welcome to work on it if u can.

Okay Thanks, @AbdelkhalekESI I will start working on it.
